[[providers.fortanixdsm]]
api_endpoint = "https://sdkms.fortanix.com"
api_key = "$FORTANIX_DSM_API_KEY"
signing_keys = [
    { chain_ids = ["$CHAIN_ID"], type = "account", key_id = "72e9ed9e-9eb4-46bd-a135-e78ed9bfd611" },
    { chain_ids = ["$CHAIN_ID"], type = "consensus", key_name = "My Key" },
]
